### ISSUE TITLE
Complete ML Engines Table

### ISSUE THREAD

**Issue by nsosio** [premAI-io/benchmarks#149]
Add the missing engines in the ml engines table

- [ ] vllm
- [ ] tensorrt
- [ ] optimum
- [ ] lightning
- [ ] exllamav2
- [ ] deepspeed
- [ ] ctransformers
- [ ] autogptq
- [ ] autoawq

Notes
- remove ROCM, Intel, Blas, Model, Tensor, ONNX, Training rows
- transpose the table

**Comment by Anindyadeep** [comment]
This is done, so closing this issue
